[package]
name = "pyoci"
version = "0.1.0"
edition = "2021"
authors = ["Allex Veldman"]
description = "Let any OCI compliant registry act as a PyPi index"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = "s"
lto = true
strip = true
codegen-units = 1

[dependencies]
bytes = "1.5.0"
exitcode = "1.1.2"
oci-spec = { version = "0.6.4", default-features = false, features = ["image", "distribution"] }
url = "2.3.1"
regex = "1.10.2"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["time"] }
reqwest = { version = "0.12.4", features = ["json", "stream"] }
askama = "0.12.1"
base64 = "0.22.1"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"

# wasm dependencies
time = { version = "0.3.36", features = ["wasm-bindgen"] }
console_error_panic_hook = "0.1.7"
wasm-bindgen = "0.2.92"
worker = {version = "0.3.0"}
tracing-web = "0.1.3"
futures = "0.3.30"
sha2 = "0.10.8"
base16ct = { version = "0.2.0", features = ["alloc"] }
urlencoding = "2.1.3"

[dependencies.web-sys]
version = "0.3.63"
features = [
  'Headers',
  'Request',
  'RequestInit',
  'Response',
  'WorkerGlobalScope',
]

[dev-dependencies]
test-case = "3.3.1"
