[package]
name = "pyoci"
version = "0.1.0"
edition = "2021"
authors = ["Allex Veldman"]
description = "Let any OCI compliant registry act as a PyPi index"
repository = "https://github.com/allexveldman/pyoci"
homepage = "https://github.com/AllexVeldman/pyoci/blob/main/README.md"
license = "MIT"

[lib]
# https://doc.rust-lang.org/reference/linkage.html
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = "s"
lto = true
strip = true
codegen-units = 1

[features]
default = ["otlp"]
otlp = [
    "dep:opentelemetry-proto",
    "dep:opentelemetry",
    "dep:opentelemetry_sdk",
    "dep:tracing-core",
    "dep:prost",
]


[dependencies]
bytes = "1.7.2"
exitcode = "1.1.2"
oci-spec = { version = "0.6.8", default-features = false, features = ["image", "distribution"] }
url = "2.5.2"
regex = "1.10.6"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["time", "env-filter", "fmt", "json"] }
reqwest = { version = "0.12.7", features = ["json", "stream"] }
askama = "0.12.1"
base64 = "0.22.1"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
sha2 = "0.10.8"
base16ct = { version = "0.2.0", features = ["alloc"] }
urlencoding = "2.1.3"
anyhow = "1.0.89"
http = "1.1.0"
axum = { version = "0.7.5", default-features = false, features = ["multipart","macros"] }
tower = { version = "0.5.0", features = ["util"] }
async-trait = "0.1.81"
pin-project = "1.1.5"
futures = "0.3.30"
time = "0.3.36"

# OTLP dependencies
opentelemetry-proto = { version = "0.25.0", default-features = false, features = ["gen-tonic-messages", "logs", "trace"], optional = true }
tracing-core = {version = "0.1.32", optional = true }
prost = {version = "0.13.2", optional = true }
# sub-dependencies of opentelemetry-proto, here to disable the default features
opentelemetry = { version = "*", default-features = false, features = ["trace"], optional = true }
opentelemetry_sdk = { version = "*", default-features = false, features = ["trace"], optional = true }


[target.'cfg(target_arch = "wasm32")'.dependencies]
worker = { version = "0.4.0", features = ["http"] }
console_error_panic_hook = "0.1.7"
tracing-web = "0.1.3"
# (sub)dependencies that need additional features for wasm
wasm-bindgen = "*"
web-sys = { version = "*", features = [
    'Headers',
    'Request',
    'RequestInit',
    'Response',
    'WorkerGlobalScope',
]}
time = { version = "*", features = ["wasm-bindgen"] }
getrandom = { version = "*", features = ["js"] }

[dev-dependencies]
futures-util = "0.3.30"
indoc = "2.0.5"
mockito = "1.5.0"
test-case = "3.3.1"
tokio = { version = "1.40.0", features = ["macros"]}
