[package]
name = "pyoci"
version = "0.1.0"
edition = "2021"
authors = ["Allex Veldman"]
description = "Let any OCI compliant registry act as a PyPi index"
repository = "https://github.com/allexveldman/pyoci"
homepage = "https://github.com/AllexVeldman/pyoci/blob/main/README.md"
license = "MIT"

[[bin]]
name = "pyoci"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = "s"
lto = true
strip = "symbols"

[features]
default = ["otlp"]
# TODO: check if otlp can be disabled
otlp = [
    "dep:opentelemetry-proto",
    "dep:opentelemetry",
    "dep:opentelemetry_sdk",
    "dep:tracing-core",
    "dep:prost",
]


[dependencies]
bytes = "1.7.2"
exitcode = "1.1.2"
oci-spec = { version = "0.6.8", default-features = false, features = ["image", "distribution"] }
url = "2.5.2"
regex = "1.10.6"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["time", "env-filter", "fmt", "json"] }
reqwest = { version = "0.12.8", default-features = false, features = ["json", "stream", "rustls-tls"] }
askama = "0.12.1"
base64 = "0.22.1"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
sha2 = "0.10.8"
base16ct = { version = "0.2.0", features = ["alloc"] }
urlencoding = "2.1.3"
anyhow = "1.0.89"
http = "1.1.0"
tower = { version = "0.5.1", features = ["util"] }
async-trait = "0.1.81"
pin-project = "1.1.5"
futures = "0.3.30"
time = "0.3.36"
axum = { version = "0.7.5", default-features = false, features = ["multipart","macros", "tokio", "http1"] }
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread", "signal", "time"] }
tokio-util = "0.7.12"

# OTLP dependencies
opentelemetry-proto = { version = "0.7.0", default-features = false, features = ["gen-tonic-messages", "logs", "trace"], optional = true }
tracing-core = {version = "0.1.32", optional = true }
prost = {version = "0.13.2", optional = true }
# sub-dependencies of opentelemetry-proto, here to disable the default features
opentelemetry = { version = "*", default-features = false, features = ["trace"], optional = true }
opentelemetry_sdk = { version = "*", default-features = false, features = ["trace"], optional = true }



[dev-dependencies]
futures-util = "0.3.30"
indoc = "2.0.5"
mockito = "1.5.0"
test-case = "3.3.1"
tokio = { version = "1.40.0", features = ["test-util"]}
