[package]
name = "pyoci"
version = "0.1.0"
edition = "2021"
authors = ["Allex Veldman"]
description = "Let any OCI compliant registry act as a PyPi index"

[workspace]
members = ["pyoci_cli", "pyoci_worker"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = "s"
lto = true
strip = true
codegen-units = 1

[dependencies]
bytes = "1.5.0"
exitcode = "1.1.2"
oci-spec = { version = "0.6.4", default-features = false, features = ["image", "distribution"] }
serde = { version = "1.0.193", features = ["derive"] }
url = "2.3.1"
regex = "1.10.2"
tracing = "0.1.40"


[dev-dependencies]
test-case = "3.3.1"
