[package]
name = "pyoci"
version = "0.1.0"
edition = "2021"
authors = ["Allex Veldman"]
description = "Let any OCI compliant registry act as a PyPi index"
repository = "https://github.com/allexveldman/pyoci"
homepage = "https://github.com/AllexVeldman/pyoci/blob/main/README.md"
license = "MIT"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = "s"
lto = true
strip = true
codegen-units = 1

[dependencies]
bytes = "1.7.1"
exitcode = "1.1.2"
oci-spec = { version = "0.6.8", default-features = false, features = ["image", "distribution"] }
url = "2.5.2"
regex = "1.10.6"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["time", "env-filter", "fmt", "json"] }
reqwest = { version = "0.12.7", features = ["json", "stream"] }
askama = "0.12.1"
base64 = "0.22.1"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
sha2 = "0.10.8"
base16ct = { version = "0.2.0", features = ["alloc"] }
urlencoding = "2.1.3"
anyhow = "1.0.89"
http = "1.1.0"
axum = { version = "0.7.5", default-features = false, features = ["multipart","macros"] }

# wasm dependencies
time = { version = "0.3.36", features = ["wasm-bindgen"] }
console_error_panic_hook = "0.1.7"
wasm-bindgen = "0.2.93"
worker = { version = "0.4.0", features = ["http"] }
tracing-web = "0.1.3"
futures = "0.3.30"
getrandom = { version = "*", features = ["js"] }

# OTLP dependencies
opentelemetry-proto = { version = "0.7.0", default-features = false, features = ["gen-tonic-messages", "logs", "trace"] }
# sub-dependencies of opentelemetry-proto, here to disable the default features
opentelemetry = { version = "*", default-features = false, features = ["trace"] }
opentelemetry_sdk = { version = "*", default-features = false, features = ["trace"] }

tracing-core = "0.1.32"
prost = "0.13.2"
tower = {version = "0.5.0", features = ["util"]}
async-trait = "0.1.81"
pin-project = "1.1.5"


[dependencies.web-sys]
version = "0.3.63"
features = [
  'Headers',
  'Request',
  'RequestInit',
  'Response',
  'WorkerGlobalScope',
]

[dev-dependencies]
futures-util = "0.3.30"
indoc = "2.0.5"
mockito = "1.5.0"
test-case = "3.3.1"
tokio = { version = "1.40.0", features = ["macros"]}
