comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  hide_project_coverage: true
ignore:
  - "src/cf.rs"  # Requires a WASM async runtime, build checks compilation, examples check runtime.
