coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

comment:
  layout: "condensed_header, condensed_files"
  hide_project_coverage: false
