name: pyoci

services:
  registry:
    image: docker.io/library/registry:2
    ports:
      - 5000:5000
    restart: always
    volumes:
      - ./config/config.yaml:/etc/docker/registry/config.yml:Z
      - ./config/tls:/etc/docker/registry/certs:Z

  registry-ui:
    image: joxit/docker-registry-ui:latest
    restart: always
    depends_on:
      - registry
    ports:
      - 8080:80
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Docker Registry UI
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
#      - REGISTRY_URL=http://localhost:5000
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - NGINX_PROXY_HEADER_Authorization=Token Foobar
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=false
      - CATALOG_ELEMENTS_LIMIT=1000

  otlp-collector:
    image: otel/opentelemetry-collector:0.103.0
    restart: always
    ports:
      - 4317:4317
      - 4318:4318
      - 55679:55679
