name: Cleanup

on:
  workflow_dispatch:
  schedule:
    # Run every Sunday at midnight
    - cron: '0 0 * * 0'

permissions:
  packages: write

jobs:
  remove-hello-world:
    name: Remove hello_world
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - run: >-
          curl -L -X DELETE
          -H "Accept: application/vnd.github+json"
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"
          -H "X-GitHub-Api-Version: 2022-11-28"
          https://api.github.com/users/allexveldman/packages/container/hello_world
