name: Deploy

on:
  workflow_call:
    inputs:
      version:
        description: 'Version to deploy'
        type: string
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy'
        type: string

# Prevent parallel deployments
concurrency:
  group: ${{ github.workflow }}-pyoci.com
  cancel-in-progress: false


jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    timeout-minutes: 10

    permissions:
      id-token: write

    environment:
      name: pyoci.com
      url: https://pyoci.com

    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: >
            az containerapp revision copy
            --name pyoci
            --resource-group PyOCI
            --image ghcr.io/allexveldman/pyoci:${{ inputs.version }}
            --tags version=${{ inputs.version }} sha=${{ github.sha }}


  examples:
    name: Examples
    needs: [deploy]
    uses: ./.github/workflows/examples.yaml
    permissions:
      packages: write
      contents: read
