name: "PR Title"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      # Verify if the PR title complies with our release-please config
      - uses: amannn/action-semantic-pull-request@v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            feature
            fix
            perf
            revert
            docs
            chore
            refactor
            test
            build
            ci
            deps
          requireScope: false
