name: Test

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    timeout-minutes: 10

    permissions:
      contents: read

    steps:
      - uses: extractions/setup-just@v3
      - uses: actions/checkout@v6
        with:
            fetch-depth: 0
      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: actions/cache@v5
        with:
          path: |
            ~/.cargo
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Test
        run: just test-coverage

      - name: Store coverage report
        uses: actions/upload-artifact@v7
        with:
          name: lcov
          path: lcov.info

      - name: Save PR number
        run: echo ${{ github.event.number }} > ./pr.txt

      - uses: actions/upload-artifact@v7
        with:
          name: pr
          path: pr.txt
